version: '3.7'

services:
  cockroachdb-node1:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node1
    command: start --insecure --advertise-addr=cockroachdb-node1 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    ports:
      - "26257:26257" # CockroachDB default port for the first node
      - "8080:8080"   # Admin UI for the first node
    networks:
      - cockroachdb-net

  cockroachdb-node2:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node2
    command: start --insecure --advertise-addr=cockroachdb-node2 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net

  cockroachdb-node3:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node3
    command: start --insecure --advertise-addr=cockroachdb-node3 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net

  cockroachdb-node4:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node4
    command: start --insecure --advertise-addr=cockroachdb-node4 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net

  cockroachdb-node5:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node5
    command: start --insecure --advertise-addr=cockroachdb-node5 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net

  cockroachdb-node6:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node6
    command: start --insecure --advertise-addr=cockroachdb-node6 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net
  cockroachdb-node7:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node7
    command: start --insecure --advertise-addr=cockroachdb-node7 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net
  cockroachdb-node8:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node8
    command: start --insecure --advertise-addr=cockroachdb-node8 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net
  cockroachdb-node9:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node9
    command: start --insecure --advertise-addr=cockroachdb-node9 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net
  cockroachdb-node10:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node10
    command: start --insecure --advertise-addr=cockroachdb-node10 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net
  cockroachdb-node11:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node11
    command: start --insecure --advertise-addr=cockroachdb-node11 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net
  cockroachdb-node12:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node12
    command: start --insecure --advertise-addr=cockroachdb-node12 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net
  cockroachdb-node13:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node13
    command: start --insecure --advertise-addr=cockroachdb-node13 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3,cockroachdb-node4,cockroachdb-node5
    networks:
      - cockroachdb-net


  cockroachdb-sql:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-sql
    depends_on:
      - cockroachdb-node1
#    command: sql --insecure --host=cockroachdb-node1
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - cockroachdb-net
    environment:
      COCKROACH_HOST: "cockroachdb-node1"

  cockroachdb-init:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-init
    depends_on:
      - cockroachdb-node1
    command: [ "init", "--insecure", "--host=cockroachdb-node1:26257" ]
    networks:
      - cockroachdb-net

networks:
  cockroachdb-net:
    driver: bridge
