apiVersion: v1
kind: Service
metadata:
  name: minio-loadbalancer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
  selector:
    app: minio
