apiVersion: apps/v1
# Stateful applications
kind: StatefulSet
metadata:
  # Unique name for the stateful set
  name: minio
spec:
  # Which headless service the stateful set is associated with
  serviceName: "minio-headless"
  # How many pods to maintain
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: minio
  # The pod template for pods in the stateful set
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}:{{ .Values.minio.tag }}
          command:
            - /bin/sh
          args:
            - "-c"
            - >
              minio server $(for i in $(seq 0 $(({{ .Values.replicaCount }} - 1))); do echo http://minio-$i.minio-headless.default.svc.cluster.local/data; done) --console-address ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.accessKey }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.secretKey }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        # One pod needs read write
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
